### ISSUE TITLE
Pulls Fabric dep when installing for Forge

### ISSUE THREAD

**Issue by noncom** [LightBlueGamer/Lithereal_1.19#1]
Hey, I've added Lithereal to a Forge modpack and it pulled the Fabric lib dependency.
Though the modpack works, this should be fixed, I believe.

It pulled `fabric-api-0.72.0+1.19.3.jar` for `lithereal-0.1.0-1.19.2.jar` while on Forge-43.2.3`.
I used the CurseForge launcher to manage the modpack.

**Comment by LightBlueGamer** [comment]
I believe this is caused by CurseForge seeing that Lithereal has a fabric dependency listed although just for the fabric version of it but sees it in general and thus pulls in the fabric API automatically I will see about making fabric as a dependency only on the fabric version of the mod so it wont get pulled up by Curseforge
